import type { AppStore } from "@/lib/types";

function offsetHours(hours: number) {
  const value = new Date();
  value.setHours(value.getHours() + hours);
  return value.toISOString();
}

function todayAt(hour: number, minute: number, dayOffset = 0) {
  const value = new Date();
  value.setDate(value.getDate() + dayOffset);
  value.setHours(hour, minute, 0, 0);
  return value.toISOString();
}

export function createSeedStore(): AppStore {
  const now = new Date().toISOString();

  return {
    meta: {
      version: 1,
      lastUpdatedAt: now,
    },
    users: [
      {
        id: "user-admin",
        name: "Nadia Salsabila",
        email: "admin@iftarrelay.id",
        password: "ramadan123",
        role: "admin",
        avatarUrl: "/images/avatar-1.png",
      },
      {
        id: "user-merchant",
        name: "Rafi Maulana",
        email: "merchant@iftarrelay.id",
        password: "ramadan123",
        role: "merchant",
        avatarUrl: "/images/avatar-1.png",
        merchantId: "merchant-tebet-senja",
      },
      {
        id: "user-operator",
        name: "Aulia Rahman",
        email: "operator@iftarrelay.id",
        password: "ramadan123",
        role: "operator",
        avatarUrl: "/images/avatar-1.png",
        nodeId: "node-masjid-tebet",
      },
    ],
    merchants: [
      {
        id: "merchant-tebet-senja",
        name: "Warung Senja Tebet",
        ownerName: "Rafi Maulana",
        area: "Tebet, Jakarta Selatan",
        active: true,
        phone: "+62 812-8000-1111",
        etaMinutes: 12,
        rating: 4.9,
        specialty: "Nasi box iftar premium",
        logoUrl: "/images/logo.png",
        imageUrl: "/images/merchant.png",
      },
      {
        id: "merchant-palmerah-lentera",
        name: "Dapur Lentera Palmerah",
        ownerName: "Siska Nur",
        area: "Palmerah, Jakarta Barat",
        active: true,
        phone: "+62 812-8000-2222",
        etaMinutes: 18,
        rating: 4.8,
        specialty: "Paket buka hemat keluarga",
        logoUrl: "/images/logo.png",
        imageUrl: "/images/food-package.png",
      },
      {
        id: "merchant-cikini-rempah",
        name: "Kedai Rempah Cikini",
        ownerName: "Yusuf Hamdan",
        area: "Cikini, Jakarta Pusat",
        active: true,
        phone: "+62 812-8000-3333",
        etaMinutes: 15,
        rating: 4.7,
        specialty: "Menu rumahan dan takjil",
        logoUrl: "/images/logo.png",
        imageUrl: "/images/charity-box.png",
      },
    ],
    nodes: [
      {
        id: "node-masjid-tebet",
        name: "Masjid Raya Tebet",
        type: "masjid",
        area: "Tebet",
        contactName: "Ustaz Hanan",
        contactPhone: "+62 812-2000-1001",
        active: true,
        imageUrl: "/images/mosque.png",
      },
      {
        id: "node-komunitas-palmerah",
        name: "Komunitas Palmerah Bergerak",
        type: "komunitas",
        area: "Palmerah",
        contactName: "Dina Azzahra",
        contactPhone: "+62 812-2000-1002",
        active: true,
        imageUrl: "/images/charity-box.png",
      },
    ],
    portions: [
      {
        id: "portion-tebet-01",
        merchantId: "merchant-tebet-senja",
        title: "Nasi Box Ayam Bakar Tebet",
        description:
          "Paket siap diambil pukul 17.10-17.35 dan cocok untuk penyaluran cepat di area Tebet.",
        totalPortions: 40,
        availablePortions: 12,
        sponsoredPortions: 18,
        distributedPortions: 8,
        price: 28000,
        sponsorPrice: 25000,
        pickupStartAt: todayAt(17, 10),
        pickupEndAt: todayAt(17, 35),
        expiresAt: offsetHours(2),
        status: "distributing",
        assignedNodeId: "node-masjid-tebet",
        tags: ["mudah diambil", "radius 3 km", "halal"],
        lastUpdatedAt: offsetHours(-1),
        imageUrl: "/images/food-package.png",
      },
      {
        id: "portion-palmerah-01",
        merchantId: "merchant-palmerah-lentera",
        title: "Paket Iftar Hemat Palmerah",
        description:
          "Menu nasi ayam suwir, kurma, dan air mineral. Siap diambil untuk penyaluran di area Palmerah.",
        totalPortions: 30,
        availablePortions: 18,
        sponsoredPortions: 0,
        distributedPortions: 0,
        price: 26000,
        sponsorPrice: 24000,
        pickupStartAt: todayAt(17, 5),
        pickupEndAt: todayAt(17, 30),
        expiresAt: offsetHours(3),
        status: "available",
        assignedNodeId: "node-komunitas-palmerah",
        tags: ["siap saji", "keluarga", "pengambilan cepat"],
        lastUpdatedAt: offsetHours(-0.5),
        imageUrl: "/images/charity-box.png",
      },
      {
        id: "portion-cikini-01",
        merchantId: "merchant-cikini-rempah",
        title: "Bubur Kampiun dan Nasi Rempah",
        description:
          "Paket kolaborasi dengan komunitas relawan yang sudah habis tersalurkan sebelum magrib.",
        totalPortions: 24,
        availablePortions: 0,
        sponsoredPortions: 24,
        distributedPortions: 24,
        price: 30000,
        sponsorPrice: 27000,
        pickupStartAt: todayAt(16, 45),
        pickupEndAt: todayAt(17, 15),
        expiresAt: offsetHours(-1),
        status: "completed",
        assignedNodeId: "node-masjid-tebet",
        tags: ["tersalurkan penuh", "selesai"],
        lastUpdatedAt: offsetHours(-3),
        imageUrl: "/images/banner.png",
      },
      {
        id: "portion-tebet-02",
        merchantId: "merchant-tebet-senja",
        title: "Takjil Box Kurma dan Roti",
        description:
          "Paket kecil yang dialihkan ke komunitas lain karena voucher awal belum digunakan.",
        totalPortions: 18,
        availablePortions: 4,
        sponsoredPortions: 10,
        distributedPortions: 0,
        price: 26000,
        sponsorPrice: 24000,
        pickupStartAt: todayAt(16, 55),
        pickupEndAt: todayAt(17, 20),
        expiresAt: offsetHours(1),
        status: "rerouted",
        assignedNodeId: "node-komunitas-palmerah",
        tags: ["dialihkan", "siap relawan"],
        lastUpdatedAt: offsetHours(-0.4),
        imageUrl: "/images/takjil-roti.png",
      },
    ],
    transactions: [
      {
        id: "tx-001",
        portionId: "portion-tebet-01",
        donorName: "Nadia Putri",
        donorEmail: "nadia@donatur.id",
        donorPhone: "081280009001",
        sponsoredPortions: 8,
        amount: 200000,
        status: "paid",
        paymentChannel: "QRIS Mayar",
        mayarInvoiceId: "MAYAR-TX001-8841",
        mayarTransactionId: "trx-paid-001",
        mayarPaymentUrl: "https://checkout.mayar.id/mock/MAYAR-TX001-8841",
        checkoutPath: "/checkout/tx-001",
        mayarQrString: "MAYARIFTAR8841NADIA",
        createdAt: offsetHours(-4),
        expiresAt: offsetHours(-3),
        paidAt: offsetHours(-3.5),
        voucherId: "voucher-001",
        notes: "Pembayaran QRIS berhasil diterima.",
        mayarWebhookPayload: JSON.stringify({
          event: "payment.received",
          data: { id: "trx-paid-001" },
        }),
      },
      {
        id: "tx-002",
        portionId: "portion-tebet-01",
        donorName: "Komunitas Lentera",
        donorEmail: "support@lentera.id",
        donorPhone: "081280009002",
        sponsoredPortions: 10,
        amount: 250000,
        status: "paid",
        paymentChannel: "Payment Link",
        mayarInvoiceId: "MAYAR-TX002-2251",
        mayarTransactionId: "trx-paid-002",
        mayarPaymentUrl: "https://checkout.mayar.id/mock/MAYAR-TX002-2251",
        checkoutPath: "/checkout/tx-002",
        mayarQrString: "MAYARIFTAR2251LENTERA",
        createdAt: offsetHours(-2),
        expiresAt: offsetHours(-1),
        paidAt: offsetHours(-1.5),
        voucherId: "voucher-002",
        notes: "Voucher aktif dan menunggu relawan mengambil paket.",
        mayarWebhookPayload: JSON.stringify({
          event: "payment.received",
          data: { id: "trx-paid-002" },
        }),
      },
      {
        id: "tx-003",
        portionId: "portion-palmerah-01",
        donorName: "Budi Rahman",
        donorEmail: "budi@donatur.id",
        donorPhone: "081280009003",
        sponsoredPortions: 6,
        amount: 144000,
        status: "pending",
        paymentChannel: "QRIS Mayar",
        mayarInvoiceId: "MAYAR-TX003-9018",
        mayarTransactionId: "trx-pending-003",
        mayarPaymentUrl: "https://checkout.mayar.id/mock/MAYAR-TX003-9018",
        checkoutPath: "/checkout/tx-003",
        mayarQrString: "MAYARIFTAR9018BUDI",
        createdAt: offsetHours(-0.4),
        expiresAt: offsetHours(0.6),
        notes: "Menunggu pembayaran dari donatur melalui Mayar.",
      },
      {
        id: "tx-004",
        portionId: "portion-tebet-02",
        donorName: "Mayar Ramadan Fund",
        donorEmail: "impact@mayar.id",
        donorPhone: "081280009004",
        sponsoredPortions: 10,
        amount: 240000,
        status: "paid",
        paymentChannel: "Virtual Account",
        mayarInvoiceId: "MAYAR-TX004-7720",
        mayarTransactionId: "trx-paid-004",
        mayarPaymentUrl: "https://checkout.mayar.id/mock/MAYAR-TX004-7720",
        checkoutPath: "/checkout/tx-004",
        mayarQrString: "MAYARIFTAR7720FUND",
        createdAt: offsetHours(-3),
        expiresAt: offsetHours(-2),
        paidAt: offsetHours(-2.5),
        voucherId: "voucher-003",
        notes: "Dialihkan otomatis ke komunitas setelah batas penggunaan awal terlewati.",
        mayarWebhookPayload: JSON.stringify({
          event: "payment.received",
          data: { id: "trx-paid-004" },
        }),
      },
    ],
    vouchers: [
      {
        id: "voucher-001",
        code: "VCR-TEBET-401",
        portionId: "portion-tebet-01",
        transactionId: "tx-001",
        merchantId: "merchant-tebet-senja",
        assignedNodeId: "node-masjid-tebet",
        recipientAlias: "Penerima Tebet A",
        portionCount: 8,
        status: "redeemed",
        expiresAt: offsetHours(2),
        qrPayload: "iftarrelay://voucher/VCR-TEBET-401",
        createdAt: offsetHours(-3.5),
        redeemedAt: offsetHours(-2.5),
        proofActivityId: "dist-001",
        imageUrl: "/images/digital-voucher.png",
      },
      {
        id: "voucher-002",
        code: "VCR-TEBET-598",
        portionId: "portion-tebet-01",
        transactionId: "tx-002",
        merchantId: "merchant-tebet-senja",
        assignedNodeId: "node-masjid-tebet",
        recipientAlias: "Relawan Masjid Tebet",
        portionCount: 10,
        status: "active",
        expiresAt: offsetHours(1),
        qrPayload: "iftarrelay://voucher/VCR-TEBET-598",
        createdAt: offsetHours(-1.5),
        imageUrl: "/images/digital-voucher.png",
      },
      {
        id: "voucher-003",
        code: "VCR-MGR-220",
        portionId: "portion-tebet-02",
        transactionId: "tx-004",
        merchantId: "merchant-tebet-senja",
        assignedNodeId: "node-komunitas-palmerah",
        recipientAlias: "Komunitas Palmerah Bergerak",
        portionCount: 10,
        status: "rerouted",
        expiresAt: offsetHours(0.5),
        qrPayload: "iftarrelay://voucher/VCR-MGR-220",
        createdAt: offsetHours(-2.4),
        imageUrl: "/images/digital-voucher.png",
      },
    ],
    distributions: [
      {
        id: "dist-001",
        voucherId: "voucher-001",
        portionId: "portion-tebet-01",
        nodeId: "node-masjid-tebet",
        actorName: "Aulia Rahman",
        actorRole: "Petugas lapangan",
        locationLabel: "Masjid Raya Tebet",
        status: "completed",
        note: "Tervalidasi dan diterima sebelum adzan magrib.",
        taskDueAt: offsetHours(-2.8),
        createdAt: offsetHours(-3.4),
        updatedAt: offsetHours(-2.5),
        proofImageUrl: "/proofs/penyaluran-tebet.svg",
        routeImageUrl: "/images/qr-scan.png",
      },
      {
        id: "dist-002",
        voucherId: "voucher-002",
        portionId: "portion-tebet-01",
        nodeId: "node-masjid-tebet",
        actorName: "Aulia Rahman",
        actorRole: "Petugas lapangan",
        locationLabel: "Pengambilan di Warung Senja Tebet",
        status: "queued",
        note: "Menunggu relawan mengambil paket dan memeriksa voucher.",
        taskDueAt: offsetHours(0.8),
        createdAt: offsetHours(-1.4),
        updatedAt: offsetHours(-1.4),
    routeImageUrl: "/images/takjil-roti.png",
      },
      {
        id: "dist-003",
        voucherId: "voucher-003",
        portionId: "portion-tebet-02",
        nodeId: "node-komunitas-palmerah",
        actorName: "Sistem penyaluran",
        actorRole: "Pengaturan otomatis",
        locationLabel: "Komunitas Palmerah Bergerak",
        status: "rerouted",
        note: "Dialihkan otomatis karena voucher awal belum digunakan mendekati waktu berbuka.",
        taskDueAt: offsetHours(0.5),
        createdAt: offsetHours(-2.3),
        updatedAt: offsetHours(-0.5),
    routeImageUrl: "/images/takjil-roti.png",
      },
      {
        id: "dist-004",
        portionId: "portion-cikini-01",
        nodeId: "node-masjid-tebet",
        actorName: "Tim Cikini Solid",
        actorRole: "Relawan komunitas",
        locationLabel: "Koridor Stasiun Cikini",
        status: "completed",
        note: "Distribusi komunitas selesai dengan dokumentasi penuh.",
        taskDueAt: offsetHours(-2.5),
        createdAt: offsetHours(-4.2),
        updatedAt: offsetHours(-2.2),
        proofImageUrl: "/proofs/iftar-cikini.svg",
        routeImageUrl: "/images/volunteer.png",
      },
    ],
    activityLogs: [
      {
        id: "log-001",
        title: "Voucher ditebus",
        description: "Voucher VCR-TEBET-401 berhasil diverifikasi di Masjid Raya Tebet.",
        entityType: "voucher",
        entityId: "voucher-001",
        actor: "Aulia Rahman",
        timestamp: offsetHours(-2.5),
        tone: "success",
      },
      {
        id: "log-002",
        title: "Pembayaran diterima",
        description: "Pembayaran MAYAR-TX002-2251 lunas dan voucher digital langsung aktif.",
        entityType: "payment",
        entityId: "tx-002",
        actor: "Konfirmasi otomatis Mayar",
        timestamp: offsetHours(-1.5),
        tone: "success",
      },
      {
        id: "log-003",
        title: "Penyaluran dialihkan",
        description:
          "Paket takjil dialihkan ke Komunitas Palmerah Bergerak agar bantuan tetap sampai.",
        entityType: "distribution",
        entityId: "dist-003",
        actor: "Sistem penyaluran",
        timestamp: offsetHours(-0.5),
        tone: "warning",
      },
      {
        id: "log-004",
        title: "Pembayaran bantuan dibuat",
        description: "Donatur Budi Rahman menyiapkan pembayaran untuk 6 porsi.",
        entityType: "transaction",
        entityId: "tx-003",
        actor: "Halaman pembayaran",
        timestamp: offsetHours(-0.4),
        tone: "info",
      },
      {
        id: "log-005",
        title: "Paket siap didukung",
        description: "Paket Iftar Hemat Palmerah diperbarui dan siap dibantu donatur.",
        entityType: "portion",
        entityId: "portion-palmerah-01",
        actor: "Dapur Lentera Palmerah",
        timestamp: offsetHours(-0.3),
        tone: "info",
      },
      {
        id: "log-006",
        title: "Distribusi komunitas selesai",
        description: "24 porsi di Cikini selesai disalurkan dengan bukti operasional lengkap.",
        entityType: "distribution",
        entityId: "dist-004",
        actor: "Tim Cikini Solid",
        timestamp: offsetHours(-2.2),
        tone: "success",
      },
    ],
    approvalRequests: [
      {
        id: "approval-001",
        actionType: "distribution-reroute",
        entityType: "distribution",
        entityId: "dist-002",
        entityLabel: "Pickup merchant Warung Senja Tebet",
        requestedByName: "Aulia Rahman",
        requestedByRole: "operator",
        requestNote:
          "Perlu dialihkan ke Komunitas Palmerah Bergerak karena relawan di Tebet sedang penuh.",
        payload: {
          nodeId: "node-komunitas-palmerah",
          note: "Mohon dialihkan agar pengambilan tetap selesai sebelum berbuka.",
        },
        status: "pending",
        createdAt: offsetHours(-0.2),
      },
    ],
  };
}
